Add artwork models's web server port option to config file
openmultiplayer/open.mp pull request #698
Opened 2023-08-01 20:12 UTC by Abyss-z94

To support some old TCP plugin like Incognito's audio plugin (The server plugin allows creating TCP servers on different ports but the client can only connect to the server through TCP port 7777).

2023-08-01 20:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/openmultiplayer/open.mp?pullRequest=698) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/openmultiplayer/open.mp?pullRequest=698) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/openmultiplayer/open.mp?pullRequest=698) it.</sub>

2023-08-07 09:39 UTC, Hual requested changes

2023-08-07 09:39 UTC, Hual commented on Server/Components/CustomModels/models.cpp
> +		webServer = new WebServer(core, modelsPath, core->getConfig().getString("network.bind"), *core->getConfig().getInt("artwork.port"), core->getConfig().getString("network.public_addr"), httpThreads);
nullptr check here since unlike getString() getInt() returns a pointer

2023-09-02 18:43 UTC, Y-Less commented
I put the default port back to 7777.  I understand why you used 7776 to avoid conflicts, but that would be a breaking change from existing server deployments.  So we need to leave that as-is, and let anyone who wants 7776 to configure it themselves.

2023-09-02 18:43 UTC, closed without merging