Update player_pool.hpp
openmultiplayer/open.mp pull request #800
Opened 2023-12-05 17:53 UTC by akosd127

Fix #792

2023-12-06 08:16 UTC, Hual commented
It would be nice if you would test your code before making a PR

2023-12-07 08:33 UTC, Hual requested changes

2023-12-07 08:33 UTC, Hual commented on Server/Source/player_pool.hpp
> +		if (config.getBool("logging.log_connection_messages"))
getBool returns a pointer that needs to be dereferenced

2023-12-07 08:33 UTC, Hual commented on Server/Source/player_pool.hpp
> +			playerConnectDispatcher.dispatch(&PlayerConnectEventHandler::onIncomingConnection, peer, addressString, port);
calling the event shouldn't be in the if statement

2023-12-08 19:13 UTC, akosd127 commented on Server/Source/player_pool.hpp
> +		if (config.getBool("logging.log_connection_messages"))
I'm sorry if I did something wrong. I just copied your code thinking it was the right way. please fix it properly and add it to the master branch. Unfortunately, English is not my native language and I don't work in IT, I'm just an avid fan

2024-01-11 00:13 UTC, akosd127 reviewed
check please

2024-01-11 18:17 UTC, Hual requested changes

2024-01-11 18:17 UTC, Hual commented on Server/Source/player_pool.hpp
> +		if (config.getBool("logging.log_connection_messages"))
This should be *config.getBool(), same with the disconnect message; not sure how that one got in

2024-02-01 17:33 UTC, closed without merging