improved dialog response checking
openmultiplayer/open.mp pull request #902
Opened 2024-03-26 21:37 UTC by atomlin-git

Maded:

- now, when processing a response to a dialogs next types: "DIALOG_STYLE_LIST", "DIALOG_STYLE_TABLIST_HEADERS", "DIALOG_STYLE_TABLIST" the number of lines in the body of the dialogue is counted, and if the "listitem" value that the player sent is more than we counted - such a response is ignored.

- limited the response parametr value from 0 to 1

Feat #866 and #867

P.S: Implemented through a loop, not a "Impl::count", since in this case the loop should be faster

2024-03-29 08:37 UTC, Hual requested changes

2024-03-29 08:37 UTC, Hual commented on Server/Components/Dialogs/dialog.cpp
> +				static_cast<DialogResponse>(sendDialogResponse.Response % 2),
Wouldn't it be better to skip dialog handling for dialogs with Response not 0 or 1?

2024-03-29 08:37 UTC, Hual commented on Server/Components/Dialogs/dialog.cpp
> +					if(data->body_[i] == '\n' && data->body_[i + 1] != '\0')
I don't see the point of the check `data->body_[i + 1] != '\0'` - you can just loop through data->body_.length()-1 and skip the last character

2024-03-29 08:37 UTC, Hual commented on Server/Components/Dialogs/dialog.cpp
> -			{
There's no point in this change

2024-03-31 08:37 UTC, Hual approved these changes

2024-04-12 10:52 UTC, ksenonadv approved these changes

2024-06-28 14:30 UTC, merged